### ISSUE TITLE
Using pathType: ImplementationSpecific return 404 (index.yaml : 404 Not Found)

### ISSUE THREAD

**Issue by zivbaz** [chartmuseum/charts#22]
When using `pathType: ImplementationSpecific ` in the ingress every call to Chartmuseum URL returns 404.
I manually change the ingress `pathType` to Prefix and it fixed the issue.
Please add support to change `pathType` as value.

**Comment by cbuto** [comment]
Closed by https://github.com/chartmuseum/charts/pull/35
