### ISSUE TITLE
can't POST anything

### ISSUE THREAD

**Issue by smirnov-mi** [chartmuseum/charts#3]
Hi guys,
I'm trying to setup my chartmuseum, it looks like I miss something.
Chart itself installed straight forward, I see the welcome to ChartMuseum start page in the browser,
I also see "health"
```
curl https://charts.my.page/health
{"healthy":true}
```
but I can't see info and can't POST anything:
```
curl https://charts.my.page/info
{"error":"not found"}

curl --data-binary "@odoo-17.0.2.tgz" https://charts.my.page/api/charts
{"error":"not found"}

```
I'm on Rancher 2.5.4, RKE k8s 1.19.4.
this is my yaml I used during the chart installation:
```
---
  env: 
    open: 
      DEBUG: "false"
  ingress:
    enabled: true
    hosts:
      - name: charts.my.page
        path: /
        tls: true
        tlsSecret: charts.my.page-tls
    certManager: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
  persistence: 
    accessMode: "ReadWriteMany"
    enabled: "true"
    size: "2Gi"
    storageClass: "rook-cephfs"
  replicaCount: "2"

```

**Comment by smirnov-mi** [comment]
i also raised another thread, since no reply here https://github.com/helm/chartmuseum/issues/402

**Comment by yurrriq** [comment]
This has long been covered in the chart README.

See https://artifacthub.io/packages/helm/chartmuseum/chartmuseum#configuration and https://github.com/chartmuseum/charts/blob/ddf80b1c/src/chartmuseum/README.md#configuration

> By default this chart will not have persistent storage, and the API service will be *DISABLED*. This protects against unauthorized access to the API with default configuration values.

| *Parameter* | *Description* | *Default* |
| -- | -- | -- |
| `env.open.DISABLE_API` | Disable all routes prefixed with /api | `true` |

**Comment by smirnov-mi** [comment]
was not easy to find and connect it with    no reply form  /info    .        Thanks , @yurrriq
