### ISSUE TITLE
chartmuseum.com website is down

### ISSUE THREAD

**Issue by kronik22** [chartmuseum/charts#8]
The chartmuseum.com website is down. Looks like there is an automated build failure on the website site. Consequently, all the documentation is offline which i need to access so that i can get my k8s persistent volume deployment working with the chartmuseum pod. I would really like to see more documentation on the --storage-local-rootdir="./chartstorage" usage, since nothing indicates where this path is auto-created on the linux file system. There are definitely some gabs in the docs with the container image running as user chartmuseum and the permissions necessary to add persistent volume. Would be helpful if you baked into the image a /storage directory with the correct permissions so that it could be used for storing the helm chart data without having to hack the pod deployment configuration with initContainers and securityContexts.

**Comment by cbuto** [comment]
outdated, closing for now
